name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - 
      name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}

    -
      name: Checkout the Repository
      uses: actions/checkout@v2
    
    - 
      name: Build the Docker image
      run: docker build -t ghcr.io/atomicbiscuit/vvot_fast_api/hellofastapi:latest --file app/Dockerfile .

    - 
      name: Push the Docker image to Container Registry
      run: docker push ghcr.io/atomicbiscuit/vvot_fast_api/hellofastapi:latest
