name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - 
      name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}

    -
      name: Checkout the Repository
      uses: actions/checkout@v3
    
    - 
      name: Build the Docker image
      run: docker build -t ghcr.io/atomicbiscuit/vvot_fast_api/hellofastapi:latest .

    - 
      name: Push the Docker image to Container Registry
      run: docker push ghcr.io/atomicbiscuit/vvot_fast_api/hellofastapi:latest

  test:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/atomicbiscuit/vvot_fast_api/hellofastapi:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      -
        name: Checkout the Repository
        uses: actions/checkout@v3
      - 
        name: Run test cases
        run: pytest test.py
